### ISSUE TITLE
Cant clone a campaign more than once

### ISSUE THREAD

**Issue by AshPowell** [knadh/listmonk#1849] opened 2024-04-30 15:05 UTC
``Error creating Campaign: pq: duplicate key value violates unique constraint "campaigns_archive_slug_key". Key (archive_slug)=(list-cleanup-22-2) already exists.``

I can't seem to be able to clone a campaign more than once. It doesn't seem to take the new cloned name as the slug, rather it uses the old campaign name.

**Comment by MaximilianKohler** [comment] 2024-04-30 18:53
Use search first. Duplicate of https://github.com/knadh/listmonk/issues/1725.

**Comment by AshPowell** [comment] 2024-04-30 19:29
> Use search first. Duplicate of https://github.com/knadh/listmonk/issues/1725.

My bad

**Closed** 2024-05-01 10:34 UTC

**Comment by AnonWG4** [comment] 2024-05-01 10:43
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0
