### ISSUE TITLE
I experienced some strange memory issue

### ISSUE THREAD

**Issue by m42e** [knadh/listmonk#227] opened 2020-11-22 11:31 UTC
After running listmonk for quite a while and sending out a newsletter, it somehow tries to consume GBs of memory. I tried it with a list of 10 recipients. Did anyone else experience such an issue? It blocked my whole server, so I couldn't access it for a few minutes.

It also reported to complete the series. Even so the docker log file showed it had issues with the connections:

```
2020/11/19 18:00:48 updates.go:74: new update v0.8.0-beta found,
2020/11/20 18:00:50 updates.go:74: new update v0.8.0-beta found,
2020/11/21 18:00:48 updates.go:74: new update v0.8.0-beta found,
2020/11/22 08:30:32 manager.go:355: start processing campaign (Unboxing und Adventskalender),
2020/11/22 08:30:32 manager.go:494: campaign (Unboxing und Adventskalender) finished,
2020/11/22 08:33:09 manager.go:271: error sending message in campaign Unboxing und Adventskalender: dial tcp: i/o timeout,
2020/11/22 08:33:09 manager.go:271: error sending message in campaign Unboxing und Adventskalender: dial tcp: i/o timeout,
2020/11/22 08:33:09 manager.go:271: error sending message in campaign Unboxing und Adventskalender: dial tcp: i/o timeout,
2020/11/22 08:33:10 manager.go:271: error sending message in campaign Unboxing und Adventskalender: dial tcp: i/o timeout,
2020/11/22 08:33:09 manager.go:271: error sending message in campaign Unboxing und Adventskalender: dial tcp: i/o timeout,
2020/11/22 08:33:09 manager.go:271: error sending message in campaign Unboxing und Adventskalender: dial tcp: i/o timeout,
2020/11/22 08:33:09 manager.go:271: error sending message in campaign Unboxing und Adventskalender: dial tcp: i/o timeout,
2020/11/22 08:33:09 manager.go:271: error sending message in campaign Unboxing und Adventskalender: dial tcp: i/o timeout,
2020/11/22 08:33:09 manager.go:271: error sending message in campaign Unboxing und Adventskalender: dial tcp: i/o timeout,
2020/11/22 08:33:12 manager.go:271: error sending message in campaign Unboxing und Adventskalender: dial tcp: i/o timeout,
2020/11/22 08:37:01 manager.go:292: error sending message 'Finished: Unboxing und Adventskalender': dial tcp: i/o timeout,
2020/11/22 08:37:59 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:38734->127.0.0.11:53: i/o timeout,
2020/11/22 08:38:08 manager.go:271: error sending message in campaign Unboxing und Adventskalender: timed out waiting for free conn in pool,
2020/11/22 08:38:10 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:60383->127.0.0.11:53: i/o timeout,
2020/11/22 08:38:20 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:52420->127.0.0.11:53: i/o timeout,
2020/11/22 08:38:30 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:32843->127.0.0.11:53: i/o timeout,
2020/11/22 08:38:40 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:37177->127.0.0.11:53: i/o timeout,
2020/11/22 08:38:50 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:44034->127.0.0.11:53: i/o timeout,
2020/11/22 08:39:00 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:48599->127.0.0.11:53: i/o timeout,
2020/11/22 08:39:10 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:52035->127.0.0.11:53: i/o timeout,
2020/11/22 08:39:20 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:45176->127.0.0.11:53: i/o timeout,
2020/11/22 08:39:30 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:47778->127.0.0.11:53: i/o timeout,
2020/11/22 08:39:30 campaigns.go:451: error fetching campaign stats: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:47778->127.0.0.11:53: i/o timeout,
2020/11/22 08:39:40 campaigns.go:93: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:49818->127.0.0.11:53: i/o timeout,
2020/11/22 08:39:40 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:49818->127.0.0.11:53: i/o timeout,
2020/11/22 08:39:50 lists.go:41: error fetching lists: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:52493->127.0.0.11:53: i/o timeout,
2020/11/22 08:39:50 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:52493->127.0.0.11:53: i/o timeout,
2020/11/22 08:40:00 manager.go:346: error fetching campaigns: dial tcp: lookup db-wai on 127.0.0.11:53: read udp 127.0.0.1:50152->127.0.0.11:53: i/o timeout,
2020/11/22 08:51:45 main.go:64: XXX,
2020/11/22 08:51:45 init.go:91: reading config: config.toml,
2020/11/22 08:51:45 init.go:167: connecting to db: db-wai:5432/listmonkwai,
2020/11/22 08:51:45 init.go:141: loading static files from: /listmonk/static,
2020/11/22 08:51:45 init.go:360: media upload provider: filesystem,
2020/11/22 08:51:45 init.go:318: loaded SMTP: newsletter@was-auch-immer.de@d1v3.de,
⇨ http server started on [::]:9000,
2020/11/22 08:51:47 updates.go:74: new update v0.8.0-beta found,
2020/11/22 08:52:10 manager.go:355: start processing campaign (Unboxing und Adventskalender - 2),
2020/11/22 08:52:11 manager.go:494: campaign (Unboxing und Adventskalender - 2) finished,
2020/11/22 08:52:23 manager.go:292: error sending message 'Finished: Unboxing und Adventskalender - 2': 554 5.5.1 Error: no valid recipients,
2020/11/22 08:52:28 manager.go:271: error sending message in campaign Unboxing und Adventskalender - 2: 503 5.5.1 Error: nested MAIL command,
```

**Comment by knadh** [comment] 2020-11-22 12:34
Hm, our instance has been running for months and has sent millions of e-mails with no memory issues. Will need to dig deeper. How many e-mails were you trying to send?

Also, from your logs, it looks like DNS resolution failed completely (DB and SMTP server). Looks like a Docker related network issue (port 53 error)

**Comment by m42e** [comment] 2021-01-25 05:28
Is there some special handling happening with the Templates? I think it is somehow related to that. I experienced it once again and I am currently trying to be able to reproduce it with a minimal setup.

**Comment by knadh** [comment] 2021-01-25 05:47
Templates are wholly unrelated. This is definitely network/connections related. From the earlier messages, it looked like the DNS look to the SMTP host from within the container was failing. Could be to do with the Docker network config. @mr-karan ?

In your Settings -> SMTP, what is the `idle timeout` you have configured?

**Comment by m42e** [comment] 2021-01-25 06:15
I am not sure it is. Maybe this has only been an additional issue. Just tried it again and it works with a small template/ content but even with a memory limit of 2GB it gets killed by the kernel. And 2GB for 1 test email should be enough, I think.

**Comment by knadh** [comment] 2021-01-25 06:51
That is very very strange. What OS is this? Our production instance that routinely sends tens of millions of e-mails barely uses few tens of MBs of memory.

Since you feel it could be connected to templating, is it possible to share your template code?

**Comment by jackdanielux** [comment] 2021-01-25 07:59
Are you by any chance using nginx ?  I faced the same issue but later found
it was an issue with my nginx setup.

**Comment by m42e** [comment] 2021-01-25 08:09
Yes and no. I normally use nginx as reverse proxy. But in my test instance i use traefik and had the same issue. I added a memory Limit for the container listmonk is running in. And the Kernel kills it after reaching 2GB of RAM (for a single mail).

**Comment by knadh** [comment] 2021-01-25 08:30
@m42e e-mailed me the template he was using and I was able to reproduce the issue locally. I think this lib that converts HTML messages to text (for older e-mail clients) is malfunctioning. Will investigate: https://github.com/knadh/listmonk/blob/6f2f361caca73a3ba6767247c2912d9065408ba8/internal/messenger/email/email.go#L117

In the meanwhile, please copy the [default template](https://github.com/knadh/listmonk/blob/master/static/email-templates/default.tpl) and customize that.

This should ideally be preinstalled with listmonk but I discovered just yesterday, to my horror, that there was a silly bug that never setup this template on the first install for anyone. It's now fixed and will be available in the next release https://github.com/knadh/listmonk/commit/05928d57b137943eb5bb0095578feb229b5a7e40.

So all the listmonk installations, instead of the default blank template, should've come with:

![image](https://user-images.githubusercontent.com/547147/105680373-a315d100-5f15-11eb-8ffe-d1336cfc514b.png)

**Comment by m42e** [comment] 2021-01-25 10:07
I disabled the "pretty tables" setting in the html2text and it looks way better now.

**Comment by jackdanielux** [comment] 2021-01-25 10:21
:)

That's why I never got this pre-installed :)

**Comment by knadh** [comment] 2021-01-30 13:25
This is fixed https://github.com/knadh/listmonk/commit/68afd61024f13cce800fe076df500347b1291752. Automatic conversion is completely removed and it is now an optional feature on the UI.

![image](https://user-images.githubusercontent.com/547147/106357487-5888c000-632c-11eb-9f09-f0ec321f6cdd.png)

**Closed by knadh** 2021-01-30 13:25 UTC
Labels: bug, needs-investigation

**Comment by RitvikSardana** [comment] 2022-08-18 06:32
![image](https://user-images.githubusercontent.com/65544983/185309906-85a6ca48-19da-45a6-b645-9670cc2d3ef0.png)

Same SMTP Settings were working fine on my local host, when deployed on Heroku, I am unable to send any emails as I am receiving this error, please look into it.

**Comment by knadh** [comment] 2022-08-18 13:05
EOF indicates that the SMTP connection broke. Maybe it's a firewall thing.
