### ISSUE TITLE
upgrade from v0.7.0 to v0.8.0 fails

### ISSUE THREAD

**Issue by sweetppro** [knadh/listmonk#222] opened 2020-11-10 20:37 UTC
running `./listmonk --upgrade` never completes...
It always says I need to backup the database and run ./listmonk --upgrade... but then never actually runs

no big deal though, it was easy enough to manually apply the migrations to the database.

**Comment by jackdanielux** [comment] 2020-11-11 02:51
It's working for me.

**Comment by knadh** [comment] 2020-11-11 03:35
> but then never actually runs

That's strange. The program just hangs with no response from the database? What version of Postgres are you on?

**Comment by mr-karan** [comment] 2020-11-11 03:53
You might need to pass the config if your config.toml is in a directory different from where you're running is this command.

`./listmonk --config /wherever/your/config.toml --upgrade`

**Comment by sweetppro** [comment] 2020-11-11 07:17
> > but then never actually runs
> 
> That's strange. The program just hangs with no response from the database? What version of Postgres are you on?

10.14

**Comment by knadh** [comment] 2020-11-11 11:51
> you need to backup your database

That's a prompt where you've enter `y/n` to continue. Did you accidentally miss that bit?

**Comment by sweetppro** [comment] 2020-11-11 12:12
> That's a prompt where you've enter `y/n` to continue. Did you accidentally miss that bit?

there was definitely no prompt, and my config.toml file was in the same directory.
I tried at least 10-15 times with the same result before I just ran the migrations manually

**Comment by cb3inco** [comment] 2020-11-12 07:52
curious, are you running docker-compose @sweetppro ?

**Comment by sweetppro** [comment] 2020-11-12 07:55
> curious, are you running docker-compose @sweetppro ?

nope, Im running Plesk Obsidian on Ubuntu 18.04

**Comment by cb3inco** [comment] 2020-11-12 08:00
Ok, I was wondering, cause I couldn't find any clarity in the documentation for running docker-compose and upgrading listmonk. I was able to find the fix. But I'm not sure that it will be helpful for you.

**Comment by knadh** [comment] 2020-11-12 08:17
@cb3inco if you're running docker-compose it's `docker-compose run --rm app ./listmonk --upgrade` (exactly like install).

**Comment by cb3inco** [comment] 2020-11-12 09:31
> @cb3inco if you're running docker-compose it's `docker-compose run --rm app ./listmonk --upgrade --yes` (exactly like install).

Thanks I ended up running the following:

```
docker-compose pull listmonkapp

docker-compose stop listmonkapp

docker-compose rm listmonkapp

docker-compose run listmonkapp ./listmonk --upgrade

docker-compose up -d listmonkapp

docker restart nginx
```

**Comment by mr-karan** [comment] 2020-11-12 11:17
@cb3inco Published [Upgrade docs](https://listmonk.app/docs/upgrade/#docker) just now. Some of those commands are not really required so next time you can refer to this doc while upgrading :+1:

**Comment by knadh** [comment] 2020-11-21 10:46
@sweetppro closing this as I've been unable to reproduce this. Since you did not get the `y/n` prompt, the only possibility is that the DB connection that happens right before it waited forever because it couldn't connect to the target somehow.

**Closed by knadh** 2020-11-21 10:46 UTC
Labels: needs-investigation

**Comment by sweetppro** [comment] 2021-02-13 14:07
I ran into the same issue just now upgrading to v0.9.0...

the issue was quite simple:
I have saved the upgrade workflow to an rtf document (on macOS)
and my texteditor changes the - (HYPHEN-MINUS) character to a - (EM DASH) character...

🤯

**Comment by knadh** [comment] 2021-02-13 15:21
>  and my texteditor changes the - (HYPHEN-MINUS) character to a - (EM DASH) character...

Ah! Saving code in Word processor docs is dangerous because of subtle, unpredictable auto-formatting. Should just put them in a plain .txt file and use a plain text editor.
