### ISSUE TITLE
AWS S3 URL rendered when custom S3-compatible service configured

### ISSUE THREAD

**Issue by benaltair** [knadh/listmonk#495] opened 2021-09-29 21:29 UTC
### Version:
 - listmonk: v2.0.0
 - OS: Configured through Heroku one-click

### Description of the bug and steps to reproduce:

1. Set custom S3-compatible backend URL
2. Set **Bucket type** to **Private**
2. Navigate to Media gallery
3. Click on or hover over the ↗ symbol to open the image in a new tab
4. Observe the Amazon URL, incongruent with the custom URL set in settings

### Screenshots:
**Settings:**
![image](https://user-images.githubusercontent.com/17771229/135350928-4a443503-fdfd-43dd-b13c-ef6849f5d502.png)

**Wrong URL in media gallery:**
![image](https://user-images.githubusercontent.com/17771229/135351049-b63a28a8-5020-4b2d-b8bc-009453443192.png)

**Comment by benaltair** [comment] 2021-09-29 21:30
Setting the bucket type for **Public** fixes the URL shown in the frontend.

**Comment by benaltair** [comment] 2021-09-29 21:39
Note: the missing thumbs are due to a separate issue #496

**Comment by knadh** [comment] 2021-10-04 16:43
I'm unable to reproduce the issue where the custom backend URL is ignored and the `amazonaws.com` URL is rendered on the uploads. In fact, the `amazonaws.com` URL is not stored in the database alongside the files and neither is it present anywhere in the codebase.

![image](https://user-images.githubusercontent.com/547147/135890788-83e72035-2499-4857-95d4-518bddceab04.png)


Can you share the API response? (`https://yoursite.com:9000/api/media`)

**Comment by benaltair** [comment] 2021-10-12 23:14
I might be missing something, but I thought this was the culprit: https://github.com/knadh/listmonk/blob/823f11ef63f1cd1585a5e4b9b0d3fa196544d36a/internal/media/providers/s3/s3.go#L39

Unfortunately we're moving in a different direction and I don't have a Listmonk instance running at this time, but I'm keeping it in mind for an upcoming project.

**Comment by knadh** [comment] 2021-10-13 05:24
> I might be missing something, but I thought this was the culprit: 

That can't be it. That bit is a fallback that only applies when the URL is empty.

> Unfortunately we're moving in a different direction and I don't have a Listmonk instance running at this time, but I'm keeping it in mind for an upcoming project.

Sure. Closing the issue for now. Please re-open if you face this again. Thanks!

**Closed by knadh** 2021-10-13 05:24 UTC
Labels: bug
