### ISSUE TITLE
Campaign finishes without sending to all recepients

### ISSUE THREAD

**Issue by dcodesdev** [knadh/listmonk#2183] opened 2024-11-29 08:08 UTC
**Version:**
 - listmonk: v4.1.0
 - OS: Ubuntu 24.04

### Description

When Running a campaign that can take some time (e.g. 2 days) if you go to **Settings > Performance > Enable Sliding Window limit** and during the campaign process if you update the value let's say you change it from 50 emails/hr to 100 emails/hr, if you save, the app prompts you to **pause** all your running campaigns and then press the restart button to reload the app.

However, if you follow the instructions the app tells you, pause the campaigns and restart the app with the given **restart button**, when restarted, the campaign status will change to **Finished** all of a sudden, without sending to all recepients.

![image](https://github.com/user-attachments/assets/ca05f70c-8c79-4dc1-8059-96f3a5eb3a85)

**Comment by MaximilianKohler** [comment] 2024-11-29 18:19
Duplicate of #2168.

**Comment by knadh** [comment] 2024-12-02 05:08
Closing in favour of #2168

**Closed by knadh** 2024-12-02 05:08 UTC
