### ISSUE TITLE
Error creating Campaign: pq: duplicate key value violates unique constraint "campaigns_archive_slug_key". Key (archive_slug)=(test-campaign-l-1-2) already exists.

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1889] opened 2024-06-05 16:18 UTC
**Version:**
 - listmonk: [eg: v1.0.0]
 - OS: [e.g. Fedora]

**Description of the bug and steps to reproduce:**

**Screenshots:**

**Comment by MaximilianKohler** [comment] 2024-06-05 19:08
Use search first. Duplicate of https://github.com/knadh/listmonk/issues/1725.

**Closed** 2024-06-06 07:32 UTC
Labels: question
