### ISSUE TITLE
cached plan must not change result type

### ISSUE THREAD

**Issue by marktopper** [knadh/listmonk#92] opened 2020-05-05 15:31 UTC
Whenever I view any page (besides the dashboard), this error pops up:

```
Error fetching lists: pq: cached plan must not change result type
```

**Comment by knadh** [comment] 2020-05-05 17:15
I Googled a bit and it looks like Postgres throws this error when mid-query, table schemas are modified. listmonk doesn't do that, except for when `--install` is run. Could you confirm if there are any external processes accessing the listmonk schema?

**Comment by marktopper** [comment] 2020-05-05 17:40
Sadly, I cannot confirm that, since that doesn't seem to be the case.
I am using the Docker instances `demo-app` and `demo-db` to run this.

**Comment by knadh** [comment] 2020-05-18 17:32
Have you been able to figure this out? Closing this as I've been unable to reproduce or find any further information on this.

**Closed by knadh** 2020-05-18 17:32 UTC
Labels: question

**Comment by knadh** [comment] 2022-04-26 12:46
This happens when the Postgres schema has changed while the app is connected to it. Unsure how that's happening, but restarting the app once should fix it.

**Comment by masterkain** [comment] 2022-04-26 12:50
thanks, I'm observing that it has stopped, not sure what's going on but here's a screen of the timeframes, in case it helps someone.

I also noticed that when this happens all the settings have been wiped. I'm a new user coming from sendy and this is kinda worrying but I'm not sure where to start help debugging.

<img width="649" alt="Screen Shot 2022-04-26 at 14 47 30" src="https://user-images.githubusercontent.com/12844/165303192-fe310d3f-cf68-4bd9-a03f-a398d52e8421.png">

**Comment by knadh** [comment] 2022-04-26 12:54
> I also noticed that when this happened all the settings have been wiped (i.e. they went back to default values in db)

Ah, that indicates that the `--install` is being run over and over (wiping the DB and resetting it) somehow in your setup!

**Comment by masterkain** [comment] 2022-04-26 12:57
I see, it's probably because of the deliveryhero helm chart with these values:

```
  values:
    image:
      tag: "v2.1.0" # {"$imagepolicy": "flux-system:listmonk:tag"}
    replicaCount: 1
    database:
      create: false
      init: true
```

I guess `init` should be put to `false` after first deployment, unfortunately this way of doing things means it's not so much infra-as-code gitops friendly.

thanks!
