### ISSUE TITLE
Listmonk 3.0 Campaign Cloning Now Fails With Errors

### ISSUE THREAD

**Issue by PackMeister** [knadh/listmonk#1828] opened 2024-04-13 17:40 UTC
**Version:**
 - listmonk: 3.0.0
 - OS: Debian 12.5

**Description of the bug and steps to reproduce:**
Trying to launch a new monthly campaign using a clone of previous months campaign as starting template.
This has worked successfully for several years but for the first time when I try to clone **any ** previous campaign I now get an error like the attached screenshot.

**Screenshots:**
<img width="1380" alt="Listmonk Error While Cloning Campaign" src="https://github.com/knadh/listmonk/assets/35346304/29c67b98-10c6-4aae-aab8-5416ef18b298">

**Comment by MaximilianKohler** [comment] 2024-04-13 19:44
Duplicate of https://github.com/knadh/listmonk/issues/1725.

**Closed** 2024-04-15 06:29 UTC
