### ISSUE TITLE
Installation failure with filesystem issue

### ISSUE THREAD

**Issue by mukoshy** [knadh/listmonk#20] opened 2019-10-10 00:56 UTC
I have got the setup server ready, but the installation failed with the following error.

```
[root@letter listmonk]# ./listmonk --install
2019/10/10 00:49:51 main.go:108: reading config: config.toml
2019/10/10 00:49:51 main.go:136: unable to initialize embedded filesystem: no ID found in the file
2019/10/10 00:49:51 main.go:137: using local filesystem for static assets
2019/10/10 00:49:51 main.go:213: failed to initialize local file for assets: stat frontend/build: no such file or directory
```

I am unsure why I am having file system error, could you please advice?

**Comment by knadh** [comment] 2019-10-10 05:23
Looks like you're running a binary that doesn't have the static assets stuffed in it. Assuming you're running Linux, please download the latest release https://github.com/knadh/listmonk/releases/download/v0.2.2-alpha/listmonk_0.2.2-alpha_linux_amd64.tar.gz

**Comment by mukoshy** [comment] 2019-10-13 19:19
Thanks @knadh  it works.

However, I am having the following challenges now.

- I have to run ./listmonk each time to have it running, can I add it to systemctl enabled services?
- I configured the _config.toml_ with logo URL and favicon but they don't seem to reflect.
- It seems to run very slow when loading on the web each first time.

Could you advice?

**Comment by mukoshy** [comment] 2019-10-13 19:19
Thanks @knadh  it works.

However, I am having the following challenges now.

- I have to run ./listmonk each time to have it running, can I add it to systemctl enabled services?
- I configured the _config.toml_ with logo URL and favicon but they don't seem to reflect.
- It seems to run very slow when loading on the web each first time.

Could you advice?

**Comment by knadh** [comment] 2019-10-14 17:29
- Yes, listmonk is supposed to be run as a service. You can add a systemctl unit, or use supervisord.
- Logo and favicon, @vividvilla could you please investigate?
- Not sure why this is. Could be network. Have you inspected the requests (browser console) to see where the time's spent?

**Comment by mukoshy** [comment] 2019-10-17 11:52
@vividvilla do you have any update for me regarding the custom logo and favicon?

**Comment by vividvilla** [comment] 2019-10-17 14:27
@mukoshy Haven't checked this, will try reproducing the issue.

**Comment by mukoshy** [comment] 2019-11-25 19:58
@vividvilla any update for me regarding the custom listmonk app logo/favicon?

Also, I am having an issue with media upload, it seems to upload but then images and file links are broken. How do I troubleshoot this? @knadh

**Comment by vividvilla** [comment] 2019-11-25 20:38
My bad, lost track of this issue. Added to my to-do for tomorrow. Will let you know once I debug.

**Comment by mr-karan** [comment] 2019-11-26 03:44
@mukoshy Guessing you're running the older version, there was a fix for this in the latest release. Please try that (also, not there are some configuration changes for upload, you can go through the config.toml.sample to see the new fields). 

Ref: #30

**Comment by knadh** [comment] 2019-11-30 13:05
@mukoshy `logo_url` and `favicon_url` in config.toml reflect on all public pages such as the unsubscription page. Tested this. If it's still not working for you, could you please post additional details?

**Closed by knadh** 2019-11-30 13:05 UTC
