### ISSUE TITLE
No views, nor clics ?

### ISSUE THREAD

**Issue by kdaffef** [knadh/listmonk#953] opened 2022-09-21 15:32 UTC
*** Sorry this is not a bug, but question for help !! - i couldn't switch it to question

**Version:**
 - listmonk:2.20
 - OS: vps hetzner - ubuntu via younhost

**Description of the bug and steps to reproduce:**
fine app install , no issues or error, can log and make campaign sending with no difficulty, sent emails are opened on gmail with images activated on email clients, everything seems correct in configuration, share some shots here :

I'm new, may be missing great thing ?

Thank you for any help ;-) 
Regards +++

![Settings-listmonk](https://user-images.githubusercontent.com/746103/191546592-906263ac-e9a1-48f7-841c-73ebc5ff10a2.png)

![Templates-listmonk](https://user-images.githubusercontent.com/746103/191546657-76ffcd38-8fc4-4675-b34c-bb2ca439d7a3.png)

![Logs-listmonk](https://user-images.githubusercontent.com/746103/191546711-87f53eaa-1994-4b7b-88ca-39deb8c4cc53.png)

![Campaigns-listmonk](https://user-images.githubusercontent.com/746103/191546772-cccbf79d-9871-4ec5-ad20-6506d45787c2.png)

**Comment by knadh** [comment] 2022-09-22 06:51
- Are you links wrapped with `{{ TrackLink }}`?
- Did you open the e-mail in your e-mail client and use the browser's network inspector to see whether a request is going to the tracking image?

**Comment by kdaffef** [comment] 2022-09-22 15:22
hi @knadh : i love your application, and a lot more when it works!
for not experienced, i have pasted template example from Docs,  will test again

For 2nd question, do not know to inspect this with Firefox ?
Thank you for help!!
Plz keep this piece updated and maintained ++++

**Comment by candideu** [comment] 2022-09-29 14:28
> For 2nd question, do not know to inspect this with Firefox ? Thank you for help!! Plz keep this piece updated and maintained ++++

Right-click on the page and select `Inspect (Q)`.

The Inspector should pop up. Click on the "Network" tab.

![image](https://user-images.githubusercontent.com/55474996/193058775-adf76690-0cc9-46f4-a9e5-2500a67f6635.png)

**Comment by kdaffef** [comment] 2022-09-30 06:33
thank you for help, i'm still same point,
here shot for firefox network inspector  : 

![firefox-inspector](https://user-images.githubusercontent.com/746103/193205370-a968ca90-bb04-492b-a00f-c2249787c8de.jpg)

my campaign stats are zero - even with new fesh install 

Thank you for any help

**Comment by knadh** [comment] 2022-10-01 07:08
The request list doesn't show a request going to your installation. Is there `{{ TrackView }}` in your template?

**Comment by knadh** [comment] 2022-10-02 16:59
I'm unsure what's happening here. Maybe the pixel is being blocked by your mail client or browser.

Can you share the [full raw dump](https://www.lifewire.com/how-to-view-the-source-of-a-message-in-gmail-1172105) of a sample e-mail from your inbox?

**Comment by paulrudy** [comment] 2022-10-04 00:30
@kdaffef I just did a test install and ran into the issue where opens were not being tracked. In my case, it was because I had the wrong root url in listmonk settings. Check in Settings > General that the root URL is the same as the url where your listmonk app is installed. For example, mine is installed on railway.app, and root URL was `http://localhost:9000`. I needed to change it to `https://listmonk-production.blabla.bla.railway.app`

**Comment by kdaffef** [comment] 2022-10-04 11:36
hi there,
Thank you @knadh, @paulrudy  for your feedbacks, sure will find the issue,
for now, i installed listmonk within younhost  vps instance on a subdomain, so my url installed is like : https://news.domain.fr/

This seems fine according to documentation, is there any specific port which should be opened ??
Thank you!!

otherwise this email content

--------------------------------------------------------------------------
Delivered-To: admin-name@gmail.com
Received: by 2002:a05:7300:73cb:b0:7c:e663:a939 with SMTP id v11csp163802dyd;
        Tue, 4 Oct 2022 04:24:10 -0700 (PDT)
X-Google-Smtp-Source: AMsMyM722RwBDG88r/kcUXdWW0sNKvEpI+m9j6fGujRe+qP0msOJZlPNbP5Oys7JbGBkVAkz9O7t
X-Received: by 2002:a17:90b:1f86:b0:205:d3d0:1931 with SMTP id so6-20020a17090b1f8600b00205d3d01931mr17068515pjb.211.1664882650574;
        Tue, 04 Oct 2022 04:24:10 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1664882650; cv=none;
        d=google.com; s=arc-20160816;
        b=VEfm/QWgTChV9GxJxgYAXnbSDzSJKzdRwVwv2q3ZifO9WUY1t/LsIpq/FNUPB6Xiww
         nmXo7GNFuqUTYYZF3pXy24h6Ni9pqZUr9eIRjvL9e6Gw4sVR6IUhrmETmpvQshqjaXkB
         Q3t0TJNJo8tLucMQ1rqTkLA4H9bQ67QIzZUwg7C0Non5GtWPUzazaTpwrhgkbrOxOoaw
         +z7ZDn0/x4fr1sAKOBSfECPUabVaDz0HZd2ENUMrw2fBMCZTwRUFJxOAmXBndkKvWWuD
         YLdlo6h4j7rwm765jASRtjY1z6M/vg0emkqdh62WFxgETvAaDFznQY5AnSyaUhQChPBg
         w9EA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=from:subject:to:content-transfer-encoding:list-unsubscribe
         :list-unsubscribe-post:mime-version:date:message-id:dkim-signature;
        bh=ZUXp1+GaQYlM+84Z8EHF4Rl33MCsGHxuSMTcwwLDJvc=;
        b=Tdrdd2COzOR1KnF+aT3P4oIEXJanos150LByeen5Cv4d4eXvo8XTLktyoT0y5q3Etl
         PdHl28KT0bwgDGFaxfzkR7NErXyCaE6W8WNf9VrH9FvAglqP0KoJTHiTmTWZI1YhsGYJ
         wUWHL4IXkI6ygb1NF0gzCA4p1PHdYlG8wLXZVF3f6cPfRSGlgQawrjiPbg1FANMYIybl
         7URO47+5F22XvsBxjVCFqT99W4Xi1uWMMhSNoBE8IVy0XsAu5EkPafEz6jX1EU35Kshj
         OYu/Q6CyGUzY96A2qZhC3v2ipT+uSg+CortihVLzAI5CmaCGEi9O43UTQOlDy+BbzIRo
         hoRg==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@domain.com header.s=mail header.b=aMYqgJgX;
       spf=pass (google.com: domain of kevinocs@domain.com designates 2a01:4f8:1c1e:4a0c::1 as permitted sender) smtp.mailfrom=kevinocs@domain.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=domain.com
Return-Path: <kevinocs@domain.com>
Received: from domain.com (domain.com. [2a01:4f8:1c1e:4a0c::1])
        by mx.google.com with ESMTPS id c17-20020a170902f31100b001786946655csi11449698ple.273.2022.10.04.04.24.09
        for <admin-name@gmail.com>
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Tue, 04 Oct 2022 04:24:10 -0700 (PDT)
Received-SPF: pass (google.com: domain of kevinocs@domain.com designates 2a01:4f8:1c1e:4a0c::1 as permitted sender) client-ip=2a01:4f8:1c1e:4a0c::1;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@domain.com header.s=mail header.b=aMYqgJgX;
       spf=pass (google.com: domain of kevinocs@domain.com designates 2a01:4f8:1c1e:4a0c::1 as permitted sender) smtp.mailfrom=kevinocs@domain.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=domain.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=domain.com; s=mail; t=1664882631; h=from:from:reply-to:subject:subject:date:date:message-id:message-id:
	 to:to:cc:mime-version:mime-version:content-type:content-type:
	 content-transfer-encoding:content-transfer-encoding:list-unsubscribe:
	 list-unsubscribe-post; bh=ZUXp1+GaQYlM+84Z8EHF4Rl33MCsGHxuSMTcwwLDJvc=; b=aMYqgJgXOCcVvK13YnWxAfS4ErQdo+DunTQs7JmntjtsfSPp9Nefh52T0hTP5WcDZ3ugs/ wV5kUO4V6k+HUdHkNRUWjjaP7pmV6c/xeJzTwue6AK/eX+mFk7mEPY9v0rjkYFFs2EAbf6 JDxMQBZDxfULa2sSbACKEJBMGha5Gkk=
X-Listmonk-Subscriber: afe06809-fbf7-49cf-9935-65ebdaead5c3
Message-Id: <1664882631378629362.1287.4901930544884385777@domain.com>
Date: Tue, 04 Oct 2022 13:23:51 +0200
X-Listmonk-Campaign: 0c8a577f-6b3a-4d58-ac91-221426f69e36
Mime-Version: 1.0
List-Unsubscribe-Post: List-Unsubscribe=One-Click
List-Unsubscribe: <https://news.domain.com/subscription/0c8a577f-6b3a-4d58-ac91-221426f69e36/afe06809-fbf7-49cf-9935-65ebdaead5c3>
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
To: <admin-name@gmail.com>
Subject: example campaign body 4
From: OCS <kevinocs@domain.com>

<!doctype html>
<html>
    <head>
        <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Du=
tf-8">
        <meta name=3D"viewport" content=3D"width=3Ddevice-width, initial-sc=
ale=3D1, minimum-scale=3D1">
        <base target=3D"_blank">

        <style>
            body {
                background-color: #F0F1F3;
                font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, sans-=
serif;
                font-size: 15px;
                line-height: 26px;
                margin: 0;
                color: #444;
            }

            pre {
                background: #f4f4f4f4;
                padding: 2px;
            }

            table {
                width: 100%;
                border: 1px solid #ddd;
            }
            table td {
                border-color: #ddd;
                padding: 5px;
            }

            .wrap {
                background-color: #fff;
                padding: 30px;
                max-width: 525px;
                margin: 0 auto;
                border-radius: 5px;
            }

            .button {
                background: #0055d4;
                border-radius: 3px;
                text-decoration: none !important;
                color: #fff !important;
                font-weight: bold;
                padding: 10px 30px;
                display: inline-block;
            }
            .button:hover {
                background: #111;
            }

            .footer {
                text-align: center;
                font-size: 12px;
                color: #888;
            }
                .footer a {
                    color: #888;
                    margin-right: 5px;
                }

            .gutter {
                padding: 30px;
            }

            img {
                max-width: 100%;
                height: auto;
            }

            a {
                color: #0055d4;
            }
                a:hover {
                    color: #111;
                }
            @media screen and (max-width: 600px) {
                .wrap {
                    max-width: auto;
                }
                .gutter {
                    padding: 10px;
                }
            }
        </style>
    </head>
<body style=3D"background-color: #F0F1F3;font-family: 'Helvetica Neue', 'Se=
goe UI', Helvetica, sans-serif;font-size: 15px;line-height: 26px;margin: 0;=
color: #444;">
    <div class=3D"gutter" style=3D"padding: 30px;">&nbsp;</div>
    <div class=3D"wrap" style=3D"background-color: #fff;padding: 30px;max-w=
idth: 525px;margin: 0 auto;border-radius: 5px;">
        Hey, did you notice how the template showed your first name?
Your last name is Gmail.

You have done  projects,
  You live in Bangalore!

Here is a link for you to click that will be tracked.
<a href=3D"https://news.domain.com/link/23f7d310-a6fc-4f3e-b20d=
-6ecdc810c561/0c8a577f-6b3a-4d58-ac91-221426f69e36/afe06809-fbf7-49cf-9935-=
65ebdaead5c3">Google</a>

Hey, did you notice how the template showed your first name?
Your tracking pixel is here : <img src=3D"https://news.office-callservices.=
fr/campaign/0c8a577f-6b3a-4d58-ac91-221426f69e36/afe06809-fbf7-49cf-9935-65=
ebdaead5c3/px.png" alt=3D"" />

Here is a 2nd link for you to click that will be tracked.
<a href=3D"https://news.domain.com/link/ce12caa0-5a09-4671-879f=
-775277b90251/0c8a577f-6b3a-4d58-ac91-221426f69e36/afe06809-fbf7-49cf-9935-=
65ebdaead5c3">domain.com</a>


    </div>
   =20
    <div class=3D"footer" style=3D"text-align: center;font-size: 12px;color=
: #888;">
            <p>
            Don&#39;t want to receive these e-mails?
            <a href=3D"https://news.domain.com/subscription/0c8=
a577f-6b3a-4d58-ac91-221426f69e36/afe06809-fbf7-49cf-9935-65ebdaead5c3" sty=
le=3D"color: #888;">Unsubscribe</a>
            <a href=3D"https://news.domain.com/campaign/0c8a577=
f-6b3a-4d58-ac91-221426f69e36/afe06809-fbf7-49cf-9935-65ebdaead5c3" style=
=3D"color: #888;">View in browser</a>
        </p>
        <p>Powered by <a href=3D"https://listmonk.app" target=3D"_blank" st=
yle=3D"color: #888;">listmonk</a></p>
        <img src=3D"https://news.domain.com/campaign/0c8a577f-6=
b3a-4d58-ac91-221426f69e36/afe06809-fbf7-49cf-9935-65ebdaead5c3/px.png" alt=
=3D"" />
    </div>
    <div class=3D"gutter" style=3D"padding: 30px;">&nbsp;</div>
</body>
</html>

**Comment by knadh** [comment] 2022-10-22 12:09
Closing this as it's not reproducible, unfortunately.

**Closed by knadh** 2022-10-22 12:09 UTC
Labels: needs-investigation
