### ISSUE TITLE
[URGENT!] Erroneous unsubscribes! Plus, verifying that someone unsubscribed, and when. 

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1454] opened 2023-08-14 06:33 UTC
**Version:**
 - listmonk: Updated from 2.4 to 2.5
 - OS: ubuntu

I sent a campaign on Friday with v2.4 and upgraded listmonk to v2.5 over the weekend. I noticed that one of my test emails has been erroneously unsubscribed. I have no idea when this happened because the UI only seems to record changes that we make ourselves. IE, the "updated" timestamp:
![Screenshot 2023-08-13 200738](https://github.com/knadh/listmonk/assets/3606996/27e0a810-8d51-44a5-99f7-03188b14fbe2)

"Updated" does not change when a user unsubscribes. 

This might be a bug because I checked the .sql file below and it does list the new date. 

I do not have `Include List-Unsubscribe header` enabled because I was concerned about bots clicking it. https://github.com/knadh/listmonk/issues/1078

## Searching the .sql:

I have a copy of the **database** from before and after I upgraded listmonk. I figured I could search it to see if the subscription status of the user was the same in both. 

I searched the .sql with notepad++ but it definitely has issues with [.sql?] files this large. What's a better program to use?

I looked for the email that was erroneously unsubbed and only found one entry that doesn't have any lists or unsubbed info. I searched it for the UUID of the list they were unsubbed from and also only found 1 match with no info on members of the list. 

Under
```
--
-- Data for Name: subscriber_lists; Type: TABLE DATA; Schema: public; Owner: listmonk
--

COPY public.subscriber_lists (subscriber_id, list_id, status, created_at, updated_at) FROM stdin;
```
I scrolled to the ID `4209` and found:
`4209	3	confirmed	2022-11-16 16:42:20.196076+00	2022-11-16 16:42:20.196076+00`
Which is only what it shows in the screenshot. 

### Differences in DB versions:

I compared the pre-and-post-upgrade DBs and there are some significant differences. The lines I can find the entries on are different, and the newer DB has `	{}` at the end. 

The first entries are the pre-upgrade:
```
"MJ Test" is found on line 805301:
4209	3	confirmed	2022-11-16 16:42:20.196076+00	2022-11-16 16:42:20.196076+00
Then line 1685836:
4209	3	unsubscribed	2022-11-16 16:42:20.196076+00	2023-08-13 04:41:46.027815+00	{}
```
You can see the 2nd entry **does** have the proper "updated" timestamp, even though that's not what it currently shows in my listmonk UI (see screenshot above). 

```
Other test email is found on line 805558
4208	3	unconfirmed	2022-11-17 16:26:48.550355+00	2022-11-17 16:26:48.550355+00
Then line 806149:
4208	3	unconfirmed	2022-11-17 16:26:48.550355+00	2022-11-17 16:26:48.550355+00	{}
```

## Looking for other changes:

I would like to be able to compare the before-and-after .sql files to see how many other people are unsubscribed. Is this possible? What would be the easiest way to do that? 

Well I used notepad++ again (with difficulty) and compared instances of `unsubscribed	` and my MJ Test was the only one different. 

I **was** clicking the `unsubscribe` button at the bottom of the last email I sent myself in order to test and update the favicon. I'm pretty sure I did **not** click the "unsubscribe" button, but hey, who knows. My memory is quite poor. 

I looked at my browser history and I see the instances of me clicking on it. The window title is `Unsubscribe from mailing list`. 

~~But the title of the window changes to `Unsubscribed` when you click the button (tested in private window), and I have no browser history of that.~~ Nvm, that's not valid since it overwrites after you open it again.

**EDIT**: 

I compared the timestamps of my browser history and the .sql entry: `4209	3	unsubscribed	2022-11-16 16:42:20.196076+00	2023-08-13 04:41:46.027815+00	{}`, and they both match the same `04:41` time. So it wasn't when I upgraded the DB that the issue occurred. It was when I was clicking the "unsubscribe" links to test the favicon. But this was after upgrading to v2.5 and I've never noticed a false unsubscribe in previous versions. 

The matching URL in my history shows as `https://www.google.com/url?q=https://listmonk.mysite.com/subscription/644d3333333338dae55d521/82253984444444444445df89e&source=gmail&ust=1691987662604000&usg=AOvVaw2aNayaAJHVEAwfskYLTaES`

I found some info on what those are https://webapps.stackexchange.com/questions/149188/some-codes-added-to-url-when-accessing-wikipedia-from-gmail-and-how-to-prevent-i

When I click on the "unsubscribe" link in my email (with/without images loaded) that google url does not refresh. When I visit it directly I get a "redirect notice", which is something unique, and not something I get when I click the email links. So somehow that google url is showing up in my history without me seeing the redirect. Maybe it happens subtly on the first click only? EDIT: nope. I sent myself a new campaign and every time I click it's refreshing the google url too. Strange that it doesn't refresh when I use the previous email's link. 

I'm wondering if somehow gmail/google is responsible for the false unsubscribe. 

# Confirmed!!

Holy crap I knew I wasn't just imagining things. Yes, it's 100% bugged, and since it happened so easily again it must be a bug with the new listmonk version. 

I sent myself a test campaign and with my 2nd test email I clicked on the "unsubscribe" link in the email, and did NOT click "unsubscribe" in the new window/tab that opens, yet I was unsubscribed. And the "updated" timestamp did not change. 

I removed myself from the list, and readded, in order to clear the "unsubscribed" status. Then clicked the "email-unsub" link multiple times and it didn't unsub me again. So I sent myself a new campaign, opened it, I didn't get unsubbed. I clicked on the email-unsub link, and that unsubbed me.

**Comment by MaximilianKohler** [comment] 2023-08-14 10:30
@knadh !!!

**Comment by knadh** [comment] 2023-08-15 03:04
Investigating this today.

**Comment by knadh** [comment] 2023-08-15 13:14
> I sent myself a test campaign and with my 2nd test email I clicked on the "unsubscribe" link in the email, and did NOT click "unsubscribe" in the new window/tab that opens, yet I was unsubscribed. And the "updated" timestamp did not change.

Unable to reproduce this.

- Created single and double opt-in lists.
- Add subscribers to both. Confirm opt-in for subscribers on opt-in lists.
- Send campaign.
- Click on the "Unsubscribe" link on the e-mail received on opt-in and non-optin subscribers. 
- The unsubscription page opens. Did a few Ctrl+Shift+R to refresh.
- **No automatic unsubscription happens**.
- Explicitly clicking on the "Unsubscribe" button on the page works as expected.

**Comment by MaximilianKohler** [comment] 2023-08-15 13:25
>Unable to reproduce this

Ok, I see a few immediate options then. I can roll back to the previous version (how do I do that?) and do more tests. Or I can stay on the current version and [delete the db and restore the old one](https://gist.github.com/MaximilianKohler/e5158fcfe6de80a9069926a67afcae11#restore). Given that the db content changed when the listmonk versions updated, is it going to cause problems to restore an older db?

**Comment by MaximilianKohler** [comment] 2023-08-16 00:40
> There's no piece of logic that executes on rendering the unsub page that actually does an unsubscribe.
> 
> > I sent it to a single gmail address and it happened. It just has a delay (1-2 minutes perhaps)
> 
> It could be something in Gmail, a plugin or something else that's triggering the unsub link that's embedded in the header. You can test this by disabling the `List-Unsubscribe headers` option in Settings -> Privacy and check.

I mentioned previously that I already have `List-Unsubscribe headers` disabled due to this concern. Perhaps the new version of listmonk has a bug with that though. 

I moved the "_SES bounces not recording properly_" to its own thread since you didn't address it here. 

I'm using firefox with many addons. I'll test Edge with little to none. 

I'll test non-gmail addresses.

**Comment by MaximilianKohler** [comment] 2023-08-16 03:24
## CONFIRMED:

* It's only gmail addresses.
* It's usually only the first click that causes it. If you resub the contact then click the link again it usually won't happen. 
* It does _not_ require me to click on the new tab that loads. I can close the tab without "viewing" it.
* Ah, wow, this is super weird/cool. **It's unique to gmail + a browser addon (dark reader)**. 

So probably I didn't notice it in the past because I didn't have dark reader installed yet. I will probably still roll back to listmonk version v2.4.0 and test it, just because listmonk isn't recording bounces properly in this version either. 

## Details:

I signed in on Edge and sent a test campaign to hotmail, aol, yahoo, gmail. **Only the gmail** triggered it. 

I had **4 extensions**: _dark reader, privacy badger, ublock origin, kee password manager_. I disabled all but the password manager, and resent myself a campaign. The issue didn't occur. I opened & clicked in my **firefox** browser and it did occur. 

In Edge, I enabled _dark reader and ublock_, and clicked the link, and it triggered it. 

I enabled only _dark reader_, and it triggered it. 

I disabled _dark reader and enabled ublock and privacy badger_ and it did not trigger it. Nevermind, it did happen after some delay. 

I hadn't **refreshed the gmail page** though, so _dark reader_'s colors were still active. I refreshed gmail and clicked again with only _ublock and privacy badger_ active and it didn't seem to happen. 

I sent a new campaign with _dark reader disabled and the other 3 enabled_. It didn't seem to happen.

I disabled _dark reader_ on my _other browser (firefox)_ and it automatically turned off the colors in gmail (unlike with Edge). I refreshed the page anyway, and then clicked the link of the new campaign. The **listmonk.mysite.com page** still had dark reader enabled. That was _not_ sufficient to trigger it. 

Also, disabling/enabling addons (in Edge) allows me to trigger it without resending a campaign. 

FYI, I am doing this with all email accounts set to "_don't load images_". 

I'm not using any custom headers. 

## Possible solution?

Grey out the "unsubscribe" button by default in the new tab/window that opens. And instead of a single checkbox for "_Unsubscribe from all future e-mails_", add another one for "_Unsubscribe from this {list-name} list only_".

**Comment by knadh** [comment] 2023-08-16 08:56
> Grey out the "unsubscribe" button by default in the new tab/window that opens. And instead of a single checkbox for "Unsubscribe from all future e-mails", add another one for "Unsubscribe from this {list-name} list only".

hm, it's not right for this to be integrated into listmonk. It's a simple, standard HTML form. If a plugin is executing the form incorrectly, the plugin should be fixed.

For your usecase, you can always customize the form/button behaviour using Admin -> Appearance -> Javascript.

**Closed by knadh** 2023-08-16 08:56 UTC
Labels: needs-investigation

**Comment by MaximilianKohler** [comment] 2023-08-16 09:04
Interesting... you don't care that there are probably many people receiving listmonk emails who are using Gmail and Dark Reader (and possibly other addons) who would be erroneously unsubscribed?

**Comment by knadh** [comment] 2023-08-16 09:10
I'm concerned that a plugin that causes a simple, plain form on an arbitrary webpage will be causing similar things to many other forms on many other websites. Adding a random hack to listmonk to mitigate unknown behaviour caused by a plugin (whose behaviour might change unpredictably again, of course) does not make sense.

It's just a plain form like any other HTML form. There's nothing to fix. Please report this to the plugin developers as it must surely be triggering such behaviour erroneously on many other forms, perhaps even sensitive financial/payment forms!

**Comment by MaximilianKohler** [comment] 2023-08-16 09:27
Ok, done https://github.com/darkreader/darkreader/issues/11608
